## <center>Elements Of Data Science - F2024</center>
# <center>Week 2: Python Intro/Review and Numpy<center>
### <center>9/15/2024</center>

# TODOs

- **Review** Selections from PDSH Chapter 2
- **Read** Selections from PDSH Chapter 3
- **Skim** Selections from PDSH Chapter 4
<br>
 
- Complete Week 2 Quiz (Due 1 week from today, Sep 22 @11:59pm)

### Announcements 
**Office hours** 
- Monday 6pm-6:50pm, location: DSI Conference room
- Skype, by appointment only, Tuesdays 6pm+. (link to be sent once OH requested)

# TODOs

- Ch 2. Introduction to NumPy
    - Understanding Data Types in Python
    - The Basics of NumPy Arrays
    - <span style="color:gray;">Skim:</span> Computation on NumPy Arrays: Universal Functions
    - Aggregations: Min, Max, and Everything In Between
    - <span style="color:gray;">Skim:</span> Computation on Arrays: Broadcasting
    - Comparisons, Masks, and Boolean Logic
    - Fancy Indexing
    - Sorting Arrays
    - <span style="color:gray;">Structured Data: NumPy's Structured Arrays</span>

# TODOs

- Ch 3. Data Manipulation with Pandas
    - Introducing Pandas Objects
    - Data Indexing and Selection
    - <span style="color:gray;">Operating on Data in Pandas</span>
    - Handling Missing Data
    - <span style="color:gray;">Hierarchical Indexing</span>
    - Combining Datasets: Concat and Append
    - <span style="color:gray;">Combining Datasets: Merge and Join</span>
    - Aggregation and Grouping
    - <span style="color:gray;">Pivot Tables</span>
    - <span style="color:gray;">Skim:</span>Vectorized String Operations
    - <span style="color:gray;">Working with Time Series</span>
    - <span style="color:gray;">High-Performance Pandas: eval() and query()</span>

# TODOs

- Ch 4. Visualization with Matplotlib
    - Simple Line Plots
    - Simple Scatter Plots
    - <span style="color:gray;">Visualizing Errors</span>
    - <span style="color:gray;">Density and Contour Plots</span>
    - <span style="color:gray;">Histograms, Binnings, and Density</span>
    - <span style="color:gray;">Customizing Plot Legends</span>
    - <span style="color:gray;">Customizing Colorbars</span>
    - Multiple Subplots
    - <span style="color:gray;">Text and Annotation</span>
    - <span style="color:gray;">Customizing Ticks</span>
    - <span style="color:gray;">Customizing Matplotlib: Configurations and Stylesheets</span>
    - Three-Dimensional Plotting in Matplotlib
    - <span style="color:gray;">Geographic Data with Basemap</span>
    - Visualization with Seaborn


## Getting Changes from Git
<br>

1. `cd` to the cloned class repostory
2. `git pull`
<br>

example:
```terminal
$ cd ~/proj/eods-f24
$ git pull
```

<br>
<br>

# <center>Questions?</center>
<br>
<br>


# TODAY
<br>

- Tools Review

- Getting "Help" Documentation

- Python (Review?)

- Numpy

# Tools Review

- Starting Jupyter
- Notebooks, Kernels and Virtual Environments

# Getting "Help" Documentation in Python

In [1]:
help(print)

Help on built-in function print in module builtins:

print(...)
    print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)
    
    Prints the values to a stream, or to sys.stdout by default.
    Optional keyword arguments:
    file:  a file-like object (stream); defaults to the current sys.stdout.
    sep:   string inserted between values, default a space.
    end:   string appended after the last value, default a newline.
    flush: whether to forcibly flush the stream.



Also, in ipython/jupyter:

```terminal
print?            # show docstring
print??           # show code as well
print([SHIFT+TAB] # get help in a popup
```

In [2]:
import pandas as pd


In [3]:
pd.DataFrame()

# Python (Review?)

- Whitespace Formatting
- Dynamic Typing
- Basic Data Types
- Functions
- String Formatting
- Exceptions and Try-Except
- Truthiness
- Comparisons and Logical Operators
- Control Flow
- Assert
- Sorting
- List/Dict Comprehensions
- Importing Modules
- collections Module
- Object Oriented Programming

# Whitespace Formatting

- Instead of braces or brackets to delimit blocks, use whitespace

```python
# The pound sign marks the start of a comment. Python itself
# ignores the comments, but they're helpful for anyone reading the code.
for i in [1, 2, 3, 4, 5]:
    print(i)                    # first line in "for i" block
    
    for j in [1, 2, 3, 4, 5]:
        
        print(j)                # first line in "for j" block
        print(i + j)            # last line in "for j" block
    print(i)                    # last line in "for i" block
print("done looping")
```
<br>

- 4 space indentations are conventional
- Style Guide : PEP 8 (https://www.python.org/dev/peps/pep-0008/)

In [5]:
for name in ['Matt', 'Jack', 'John']:
    print(name+ ' is a cool guy')

Matt is a cool guy
Jack is a cool guy
John is a cool guy


# Dynamic Typing

- don't need to specify type at variable creation (though they'll get one at runtime)

In [11]:
x = 'apple'

In [12]:
type(x)

str

In [2]:
x = 3
x = 3.14
x = 'apple'
x

'apple'

In [3]:
# to determine the current variable type
type(x)

str

# Basic Python Data Types

- **int** (integer): `42`

- **float** : `4.2`, `4e2`

- **bool** (boolean): `True`, `False`

- **str** (string) : `'num 42'`, `"num 42"`,\
`"""multi-line
string"""`

- **None** (null): `None`
<br>

- also `long`, `complex`, `bytes`, etc.

# Functions

In [15]:
pd.DataFrame?

In [4]:
def add_two(x):
    """Adds 2 to the number passed in."""
    return x+2


add_two(2)

4

In [5]:
help(add_two)

Help on function add_two in module __main__:

add_two(x)
    Adds 2 to the number passed in.



Reminder, also in ipython/jupyter:

  - `add_two?            # show docstring`
  - `add_two??           # show code as well`
  - `add_two([SHIFT+TAB] # get help in a popup`

# Function Arguments

- **positional arguments** must be entered in order

In [6]:
def subtract(x,y):
    return x-y

subtract(3,1)

2

- **keyword arguments** must follow positional 
- can be called in any order

In [7]:
def proportion(numer,denom,precision=2):
    return round(numer/denom,precision)

proportion(2,precision=2,denom=3)

0.67

# String Formatting

In [21]:
x = 3.1415

'the value of x is ' + str(x)

'the value of x is 3.1415'

In [19]:
type(a)

str

In [22]:
'the value of x is %0.3f' % x

'the value of x is 3.142'

In [10]:
'the value of x is {:0.10f} and not {}'.format(x, 10)

'the value of x is 3.1415000000 and not 10'

In [28]:
f'the value of x is {x:0.2f}'
# note: f-string is a literal string, prefixed with 'f', which contains expressions inside braces.

'the value of x is 3.14'

- often want to print variable values for debugging

In [12]:
f'x = {x:0.2f}'

'x = 3.14'

In [13]:
f'{x = :0.2f}' # new in 3.8

'x = 3.14'

# String Formatting Cont.

In [29]:
"""This is a multiline string.
The value of x is {}."""

'This is a multiline string.\nThe value of x is {}.'

In [31]:
"""This is a multiline string.
The value of x is {}.""".format(x)

'This is a multiline string.\nThe value of x is 3.1415.'

In [15]:
print("""This is a multiline string.
The value of x is {}.""".format(x))

This is a multiline string.
The value of x is 3.1415.


- to learn more https://realpython.com/python-string-formatting/

# Python Data Types Continued: `list`

In [16]:
# elements of a python list do not all have to be of the same type
x = [42,'e',2.0]
x

[42, 'e', 2.0]

In [17]:
x[0] # indexing

42

In [18]:
x[-1] # reverse indexing

2.0

In [19]:
x[2] = 4 # assignment
x

[42, 'e', 4]

In [20]:
x.append('a') # add a value to list
x

[42, 'e', 4, 'a']

In [21]:
value_at_1 = x.pop(1) # remove/delete at index
x

[42, 4, 'a']

# Python Data Types Continued: `dict` (Dictionary)


- Stores key:value pairs

In [51]:
x = {'b':[2,1],'a':1,'c':4} 
# or x = dict(b=2,a=1,c=4)
x

{'b': [2, 1], 'a': 1, 'c': 4}

In [52]:
# index into dictionary using key
x['b'] 

[2, 1]

In [53]:
grades = {'John':{90: 100},
          'Mike':[100, 90],
          'Julia':[100,100]}

In [67]:
grades = {'John':{'midterm': 90,
                  'final':100},
          'Mike':[100, 90],
          'Julia':[100,100]}

In [68]:
grades['John']['midterm']

90

In [55]:
# assign a value to a (new or existing) key
x['a'] = 3 
x

{'b': [2, 1], 'a': 3, 'c': 4}

In [56]:
# remove/delete
# can specify a return a value if key does not exist (here it's None), otherwise throws an exception
x.pop('eods', None) 

In [57]:
x.pop('d', None)

In [58]:
x

{'b': [2, 1], 'a': 3, 'c': 4}

# Python Data Types Continued: `dict` Cont.


In [69]:
# using the same dictionary
x

{'b': [2, 1], 'a': 3, 'c': 4}

In [29]:
# get a set of keys
x.keys()

dict_keys(['b', 'a', 'c'])

In [30]:
# get a set of values
x.values()

dict_values([[2, 1], 1, 4])

In [31]:
# get a set of (key,value) tuples
x.items()

dict_items([('b', [2, 1]), ('a', 1), ('c', 4)])

In [32]:
# get a list of (key,value) pairs
list(x.items())

[('b', [2, 1]), ('a', 1), ('c', 4)]

# Python Data Types Continued: `tuple`

- like a list, but **immutable**

In [70]:
x = (2,'e',3,4)
x

(2, 'e', 3, 4)

In [71]:
x[0] # indexing

2

In [35]:
x[0] = 3 # assignment? Nope, error: immutable`

TypeError: 'tuple' object does not support item assignment

In [72]:
a = (1,2,[10,12])

In [74]:
a[2]

[10, 12]

In [77]:
a[2] =15

TypeError: 'tuple' object does not support item assignment

In [76]:
a

(1, 2, [15, 12])

In [78]:
a[2].append(10)

In [81]:
b = (1, 2, (15, 12, 10))

In [83]:
b

(1, 2, (15, 12, 10))

# Python Data Types Continued: `set`

In [84]:
lst = [1,1,1,1,1,1,5,5,'Jack']
# lst = list(set(lst))

In [85]:
lst

[1, 1, 1, 1, 1, 1, 5, 5, 'Jack']

In [87]:
list(set(lst))

['Jack', 1, 5]

In [42]:
x = {2,'e','e'} # or set([2,'e','e'])
x

{2, 'e'}

In [43]:
x.add(1) # insert
x

{1, 2, 'e'}

In [44]:
x.remove('e') # remove/delete
x

{1, 2}

In [45]:
x.intersection({2,3})

{2}

In [46]:
x.difference({2,3})

{1}

In [47]:
x[0] # cannot index into a set

TypeError: 'set' object is not subscriptable

# Determining Length with `len`

In [48]:
len([1,2,3])

3

In [49]:
len({'a':1,'b':2,'c':3})

3

In [88]:
['a', 'p','p','l','e']

['a', 'p', 'p', 'l', 'e']

In [50]:
len('apple')

5

In [91]:
'john'[0]

'j'

# Exceptions

In [51]:
'a' + 2

TypeError: can only concatenate str (not "int") to str

## Common exceptions:
- SyntaxError
- IndentationError
- ValueError
- TypeError
- IndexError
- KeyError
- and many more https://docs.python.org/3/library/exceptions.html

# Catching Exceptions with `try`-`except`

In [52]:
try:
    'a' + 2
except TypeError as e:
    print(f"We did this on purpose, and here's what's wrong:\n{e}")

We did this on purpose, and here's what's wrong:
can only concatenate str (not "int") to str


In [53]:
try:
    set([1,2,3])[0]
except SyntaxError as e:
    print(f"Print this if there's a syntax error")
except Exception as e:
    print(f"Print this for any other error")

Print this for any other error


# Truthiness

In [95]:
False /0

ZeroDivisionError: division by zero

- boolean: `True`, `False`
<br>

- These all translate to `False`:
 - `None`
 - `[]` (empty list)
 - `{}` (empty dictionary)
 - `''` (empty string)
 - `set()`
 - `0`
 - `0.0`

# Comparison Operators

- equality: `==`
- inequality: `!=`

In [54]:
3 == 3

True

In [55]:
3 != 4

True

In [97]:
1!= False

True

 - less than: `<`
 - greater than: `>`
 - '(less than/greater than) or equal to:  `<=` , `>=`

In [102]:
3 < 4

True

# Logical Operators

- logical operators: `and`, `or`, `not`

In [104]:
(False or True and not False)

True

In [ ]:
(False or (True and True ) and not False)

In [57]:
( (3 > 5) or ((3 < 4) and (5 > 4)) ) and not (3 == 5)

True

- `any()`: at least one element is true

In [105]:
any([0,0,0])

False

- `all()`: all elements are true

In [107]:
all([True,1,False])

False

- **bitwise operators** (we'll see these in numpy and pandas) : `&` (and), `|` (or), `~` (not)

# Assert

- use `assert` to test anything we know should be true
- simple unit test
- raises exception when assertion is false, otherwise nothing

In [60]:
assert 2+2 != 4

AssertionError: 

In [109]:
assert 1 == 0, 'if this is wrong what you want to display'

AssertionError: if this is wrong what you want to display

In [110]:
# can add an error message
assert 1 == 0, "1 does not equal 0"

AssertionError: 1 does not equal 0

# Control Flow: `if`, `elif`, `else`

- `if` then `elif` then `else`

In [111]:
x = 3
if x >= 2:
    print('x > 2')
elif 0 < x < 1:
    print('0< x < 1')
elif 1 <= x < 2:
    print('0< x < 1')
else:
    print('x == 0')

x > 2


- single-line `if` then `else`

In [114]:
print("x < 0") if (x < 0) else print("x = 0")

x = 0


# More Control Flow: `for` and `while`

- `for` each element of an iterable: do something

In [120]:
a = []
for x in [0,1,2]:
    a.append(2*x**2)
a

[0, 2, 8]

- `while` something is true

In [66]:
x = 0
while x < 3:
    x += 1
x

3

# More Control Flow: `break` and `continue`

- `break` : break out of current loop

In [67]:
x = 0
while True:
    x += 1
    if x == 10:
        print(x)
        break

10


- `continue` : continue immediately to next iteration of loop

In [68]:
for name in ['John', 'Ben', 'Julia']:
    if name == 'Ben':
        continue
    print(name)

John
Julia


In [69]:
for x in range(5):
    if x == 1:
        continue
    print(x)

0
2
3
4


# Generate a Range of Numbers: `range`

In [70]:
# create list of integers from 0 up to but not including 4
a = []
for x in range(4): 
    a.append(x)
a

[0, 1, 2, 3]

In [122]:
range(10)

range(0, 10)

In [121]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [123]:
list(range(1,5)) # with a start and end+1

[1, 2, 3, 4]

In [124]:
list(range(0,100,5)) # with start, end+1 and step-size

[0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95]

# Keep track of list index or for-loop iteration: `enumerate`

In [75]:
for i,x in enumerate(['a','b','c']):
    print(i,x)

0 a
1 b
2 c


In [76]:
list(enumerate(['a','b','c']))

[(0, 'a'), (1, 'b'), (2, 'c')]

# Sorting

Two ways to sort a list:

1. by changing the list itself: `list.sort()`

In [77]:
x = [4,1,2,3]
x.sort()
assert x == [1,2,3,4], 'Not same lists'

2. without changing the list: `sorted()`

In [125]:
x = [4,1,2,3]
y = sorted(x)
assert x == [4,1,2,3]
assert y == [1,2,3,4]

# Sorting Cont.

- To sort descending, use `reverse=True`:

In [79]:
assert sorted([1,2,3,4], reverse=True) == [4,3,2,1]

- Pass a `lambda` function to 'key=' to specify what to sort by:

In [80]:
# for example, to sort a dictionary by value
d = {'a':3,'b':5,'c':1}

# recall that .items() returns a set of key,value tuples
s = sorted(d.items(), key=lambda x: x[1])

assert s == [('c', 1), ('a', 3), ('b', 5)]

In [81]:
sorted(d.items(), key=lambda x: x[0])

[('a', 3), ('b', 5), ('c', 1)]

# List Comprehensions

- Like a single line for loop over a list or other iterable

In [82]:
# which integers between 0 and 3 inclusive are divisible by 2?
is_even = []
for x in range(0,4):
    is_even.append(x%2 == 0)
is_even

[True, False, True, False]

In [83]:
[x%2 == 0 for x in range(0,4)] # using a list comprehension

[True, False, True, False]

In [84]:
# what are the indices of the vowels in 'apple'?
vowels = ['a','e','i','o','u']
[i for i,x in enumerate('apple') if x in vowels]

[0, 4]

# Dictionary Comprehension

- list comprehension but for (key,value) pairs
- can add logic to dictionary creation

In [130]:
pairs = [(1,'e'),(2,'f'),(3,'g')]

In [131]:
dict(pairs)

{1: 'e', 2: 'f', 3: 'g'}

In [135]:
# modify value and only include odd keys
{key:'value_'+ val for key,val in pairs if key%2 == 1}

{1: 'value_e', 3: 'value_g'}

# Iterables and Generators

- **Iterable**: anything we can iterate over, eg list

- **Iterator**:
    - the object doing the iterating
    - can use `.next()` to get the next value in the iterable
    - every iterator is an iterable, but reverse not always true

In [141]:
iter_obj = iter([1,2,3])

# assert next(iter_obj) == 1

In [145]:
next(iter_obj)

StopIteration: 

# Iterables and Generators Cont.

- **Generator**
 - generates values *lazily* on demand (values not stored in memory)
 - contains a `yield` operator
 - can use `.next()` to get the next value
 - or wrap in comprehension or list to generate all

In [89]:
def generate_ones(n):
    i = 0
    while i < n:
        yield 1
        i += 1

assert list(generate_ones(3)) == [1,1,1]

# Object Oriented

In [90]:
class MyClass:
    """A descriptive docstring."""
    
    # constructor
    def __init__(self,myvalue = 0):  # what happens when created
        # attributes
        self.myvalue = myvalue

    def __repr__(self):   # what gets printed out (string repr.)
        return f'MyClass(myvalue={self.myvalue})'

    # any other methods
    
    def get_value(self):
        """Return the value in myvalue."""
        return self.myvalue

In [91]:
x = MyClass(100)            # instantiate object

assert x.myvalue == 100     # access object attribute

assert x.get_value() == 100 # use object method

# Importing Modules
<br>

- Want to import a module/library? Use `import`

In [92]:
import math

math.sqrt(2)

1.4142135623730951

- Want to import a submodule or function from a module? Use `from`

In [93]:
from math import sqrt,floor

print(sqrt(2))
print(floor(sqrt(2)))

1.4142135623730951
1


# Importing Modules Cont.
<br>

- Want to import a module using an alias? Use 'as'

In [94]:
import math as m
m.sqrt(2)

1.4142135623730951

- Don't do: `import *`

```python
from math import *
# for example, what if there is a math.print() function?
# what happens when we then call print()?
```

# `collections` Module

In [95]:
from collections import Counter, defaultdict

- `Counter` : useful for counting hashable objects
- `defaultdict` : create dictionaries without checking keys
- `OrderedDict` : key,value pairs returned in order added
<br>

- others : https://docs.python.org/3.7/library/collections.html

# `collections` Module: `Counter`

In [96]:
c = Counter(['red', 'blue', 'red', 'green', 'blue', 'blue'])
c

Counter({'red': 2, 'blue': 3, 'green': 1})

In [97]:
c = Counter()
for word in ['red', 'blue', 'red', 'green', 'blue', 'blue']:
    c[word] += 1

In [98]:
c.most_common()

[('blue', 3), ('red', 2), ('green', 1)]

# `collections` Module Cont. : `defaultdict`

In [99]:
%xmode Minimal 
# reduce the amount printed when an exception is thrown

Exception reporting mode: Minimal


In [100]:
# create mapping from length of word to list of words
colors = ['red', 'blue', 'purple', 'gold', 'orange']
d = {}
for word in colors:
    d[len(word)].append(word)

KeyError: 3

In [101]:
d = {}
for word in colors:
    if len(word) in d:
        d[len(word)].append(word)
    else:
        d[len(word)] = [word]
d

{3: ['red'], 4: ['blue', 'gold'], 6: ['purple', 'orange']}

In [102]:
d = defaultdict(list)
for word in colors:
     d[len(word)].append(word)
d

defaultdict(list, {3: ['red'], 4: ['blue', 'gold'], 6: ['purple', 'orange']})

Defaultdict is a sub-class of the dictionary class that returns a dictionary-like object. The functionality of both dictionaries and defaultdict are almost same except for the fact that defaultdict never raises a KeyError. It provides a default value for the key that does not exists.

In [103]:
# Function to return a default
# values for keys that is not
# present
def def_value():
    return "Not Present"

d = defaultdict(def_value)
d["a"] = 1
d["b"] = 2
  
print(d["a"])
print(d["b"])
print(d["c"])

1
2
Not Present


# Contexts

- a context is like applying a scope with helper functions
- For example: open and write to a file

In [104]:
with open('tmp_context_example.txt','w') as f:
    f.write('test')

In [105]:
# instead of
f = open('tmp_context_example.txt','w')
f.write('test')
f.close() # this is easy to forget to do

In [106]:
# remove the example file we just created
%rm tmp_context_example.txt

# Python (Review?)

- Dynamic Typing
- Whitespace Formatting
- Basic Data Types
- Functions
- String Formatting
- Exceptions and Try-Except
- Truthiness
- Comparisons and Logical Operators
- Control Flow
- Assert
- Sorting
- List/Dict Comprehensions
- Importing Modules
- collections Module
- Object Oriented Programming

<br>
<br>

# <center>Questions?</center>
<br>
<br>

# Working with Data

Want to:
- transform and select data quickly (numpy)
<br>

- manipulate datasets: load, save, group, join, etc. (pandas)
<br>

- keep things organized (pandas)

# Intro to NumPy


<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/NumPy_logo_2020.svg/640px-NumPy_logo_2020.svg.png?1600616553332" width="200px">


Provides (from numpy.org):

- a powerful N-dimensional array object
<br>

- sophisticated (broadcasting) functions
<br>

- linear algebra and random number capabilities
<br>

- (Fourier transform, tools for integrating C/C++ and Fortran code, etc.)

# Python Dynamic Typing

In [20]:
x = 5
x = 'five'
x = 5.0

    - Note: still *strongly* typed
- Python is both a strongly typed and a dynamically typed language. 
    - Strong typing means that variables do have a type and that the type matters when performing operations on a variable. 
    - Dynamic typing means that the type of the variable is determined only during runtime.

In [22]:
x,y = 5,'five'
x+y

TypeError: unsupported operand type(s) for +: 'int' and 'str'

# Python Dynamic Typing

<div align="center"><img src="https://jakevdp.github.io/PythonDataScienceHandbook/figures/cint_vs_pyint.png" width="500px"></div>
<br>
[PDHS Chap 2.](https://jakevdp.github.io/PythonDataScienceHandbook/02.01-understanding-data-types.html)

- A C integer is essentially a label for a position in memory whose bytes encode an integer value. 
- A Python integer is a pointer to a position in memory containing all the Python object information, including the bytes that contain the integer value. 
    - **ob_refcnt**, a reference count that helps Python silently handle memory allocation and deallocation
    - **ob_type**, which encodes the type of the variable
    - **ob_size**, which specifies the size
    - **ob_digit**, which contains the actual integer value that we expect the Python variable to represent.
This extra information in the Python integer structure is what allows Python to be coded so freely and dynamically.


# NumPy Array vs Python List
- The NumPy array essentially contains a single pointer to one contiguous block of data. 

- The Python list, on the other hand, contains a pointer to a block of pointers, each of which in turn points to a full Python object like the Python integer we saw earlier. 
- The advantage of the list is flexibility: because each list element is a full structure containing both data and type information, the list can be filled with data of any desired type. Fixed-type NumPy-style arrays lack this flexibility, but are much more efficient for storing and manipulating data.

<div align="center"><img src="https://jakevdp.github.io/PythonDataScienceHandbook/figures/array_vs_list.png" width=700px></div>
<br>
<br>
<br>

[PDHS Chap 2.](https://jakevdp.github.io/PythonDataScienceHandbook/02.01-understanding-data-types.html)

# Importing NumPy

Often imported as alias `np`

In [24]:
import numpy as np
#Create an numpy array with random integers
np.random.randint(10,size=5)

array([6, 5, 0, 7, 4])

# NumPy Datatypes

<font size="5">
    
```
bool_       Boolean (True or False) stored as a byte
int_        Default integer type (same as C long; normally either int64 or int32)
intc        Identical to C int (normally int32 or int64)
intp        Integer used for indexing (same as C ssize_t; normally either int32 or int64)
int8        Byte (-128 to 127)
int16       Integer (-32768 to 32767)
int32       Integer (-2147483648 to 2147483647)
int64       Integer (-9223372036854775808 to 9223372036854775807)
uint8       Unsigned integer (0 to 255)
uint16      Unsigned integer (0 to 65535)
uint32      Unsigned integer (0 to 4294967295)
uint64      Unsigned integer (0 to 18446744073709551615)
float_      Shorthand for float64.
float16     Half precision float: sign bit, 5 bits exponent, 10 bits mantissa
float32     Single precision float: sign bit, 8 bits exponent, 23 bits mantissa
float64     Double precision float: sign bit, 11 bits exponent, 52 bits mantissa
complex_    Shorthand for complex128.
complex64   Complex number, represented by two 32-bit floats
complex128  Complex number, represented by two 64-bit floats
...
```
</font>

# NumPy Arrays

In [6]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [7]:
type(x[0])

numpy.int64

In [8]:
# use dtype to show the datatype of the array
x.dtype

dtype('int64')

In [9]:
# np arrays can only contain one datatype and default to the most flexible type
x = np.array([1,'two',3])
x

array(['1', 'two', '3'], dtype='<U21')

In [10]:
x.dtype

dtype('<U21')

In [25]:
# many different ways to create numpy arrays
np.zeros(5,dtype=int)

array([0, 0, 0, 0, 0])

In [31]:
np.ones(5, dtype=float)

array([1., 1., 1., 1., 1.])

# NumPy Array Indexing

- For single indices, works the same as list

In [33]:
x = np.arange(6)
x

array([0, 1, 2, 3, 4, 5])

In [117]:
x[0], x[-1], x[-2], x[-4]

(1, 5, 4, 2)

# NumPy Array Slicing

In [118]:
x = np.arange(5) # note that in numpy it's arange instead of range
x

array([0, 1, 2, 3, 4])

In [34]:
# return first two items, start:end (exclusive)
x[0:3]

array([0, 1, 2])

In [120]:
# missing start implies position 0
x[:4]

array([0, 1, 2, 3])

In [121]:
# missing end implies length of array
x[2:]

array([2, 3, 4])

In [122]:
# return last two items
x[-2:]

array([3, 4])

# NumPy Array Slicing with Steps

In [37]:
x

array([0, 1, 2, 3, 4, 5])

In [41]:
# return every other item from position 1 to 4 exclusive
# start:end:step_size
x[1:4:2]

array([1, 3])

# Reverse array with step-size of -1

In [125]:
x

array([0, 1, 2, 3, 4])

In [126]:
x[::-1]

array([4, 3, 2, 1, 0])

# NumPy Fancy Indexing

- Accessing multiple, non-consecutive indices at once using a list

In [43]:
x = np.arange(5,10)
x

array([5, 6, 7, 8, 9])

In [46]:
x[[0,4]]

array([5, 9])

In [129]:
x[[0,2,-1]]


array([5, 7, 9])

# Boolean Indexing using a Boolean Mask

In [47]:
x

array([5, 6, 7, 8, 9])

In [131]:
# Which indices have a value divisible by 2?
# mod operator % returns remainder of division
x%2 == 0

array([False,  True, False,  True, False])

In [48]:
x[[False,  True, False,  True, False]]

array([6, 8])

In [51]:
# Which values are divisible by 2?
x[x%2 == 0]

array([6, 8])

In [55]:
# Which values are greater than 6?
x[x <= 8]

array([5, 6, 7, 8])

# Boolean Indexing And Bitwise Operators

In [56]:
x

array([5, 6, 7, 8, 9])

In [57]:
(x%2 == 0)

array([False,  True, False,  True, False])

In [58]:
(x > 6)

array([False, False,  True,  True,  True])

In [62]:
# & compares each element pairwise
x[(x%3 == 0) & (x > 5) & (x%2==0) ]

array([6])

In [139]:
x[np.array([False, False, False,  True, False])]

array([8])

In [140]:
x[(x%2 == 0) & (x > 6)]

array([8])

# Boolean Indexing And Bitwise Operators

- and : `&` (ampersand)

In [141]:
# Which values are even AND greater than 6?
x[(x%2 == 0) & (x > 6)]

array([8])

- or : `|` (pipe)

In [65]:
# which values are even OR greater than 6?
x[(x%3 == 0) | (x > 8)]

array([6, 9])

- not : `~` (tilde)

In [143]:
( (x%2 == 0) | (x > 6) )

array([False,  True,  True,  True,  True])

In [144]:
~( (x%2 == 0) | (x > 6) )

array([ True, False, False, False, False])

In [67]:
# which values are NOT (even OR greater than 6)
x[~( (x%2 == 0) | (x > 6) )]

array([5])

- see [PDHS](https://jakevdp.github.io/PythonDataScienceHandbook/02.06-boolean-arrays-and-masks.html) for more info

# Indexing Review

- standard array indexing (including reverse/negative)
<br>

- slicing [start:end:step-size]
<br>

- fancy indexing (list/array of indices)
<br>

- boolean indexing (list/array of booleans)

# Multidimensional Lists

In [146]:
x = [[1,2,3],[4,5,6]] # list of lists
x

[[1, 2, 3], [4, 5, 6]]

In [147]:
# return first row
x[0] 

[1, 2, 3]

In [148]:
# return first row, second column
x[1][2] 

6

In [149]:
# return second column?
[row[1] for row in x]

[2, 5]

# NumPy Multidimensional Arrays

In [69]:
x = np.array([[1,2,3],[4,5,6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [70]:
x[0,1] # first row, second column

2

In [72]:
x[0,:] # first row

array([1, 2, 3])

In [153]:
x[0,:] # first row (first to last column)

array([1, 2, 3])

In [154]:
x[:,1] # second column (first to last row)

array([2, 5])

# NumPy Array Attributes

In [78]:
x = np.array([[1,2,3],[4,5,6]])

In [79]:
x.ndim # number of dimensions

2

In [80]:
x.shape # shape in each dimension

(2, 3)

In [81]:
x.size # total number of elements

6

# NumPy Operations (UFuncs)

In [82]:
x = [1,2,3]
y = [4,5,6]

In [160]:
x+y

[1, 2, 3, 4, 5, 6]

In [161]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [162]:
x+y

array([5, 7, 9])

In [163]:
%time sum(range(0,int(1e8)))

CPU times: user 1.36 s, sys: 6.17 ms, total: 1.37 s
Wall time: 1.36 s


4999999950000000

In [164]:
%time np.arange(0,int(1e8)).sum()

CPU times: user 282 ms, sys: 259 ms, total: 542 ms
Wall time: 576 ms


4999999950000000

# NumPy Broadcasting

Allows for vectorized computation on arrays of different sizes

In [83]:
# square every element in a list
x = [1,2,3]

In [84]:
x**2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [167]:
# square every element in a numpy array
x = np.array([1,2,3])

In [168]:
x**2

array([1, 4, 9])

In [85]:
a = np.array([1.0, 2.0, 3.0])
b = 2.0
a * b

array([[2., 4., 6.],
       [2., 4., 6.]])

is equivalent to 

In [170]:
a = np.array([1.0, 2.0, 3.0])
b = np.array([2.0, 2.0, 2.0])
a * b

array([2., 4., 6.])

# NumPy `random` Submodule

Provides many random sampling functions

In [86]:
from numpy.random import seed, randn

In [96]:
seed(1990)

In [100]:
randn(10)

array([ 0.36600325, -1.82556046, -0.51229396,  0.86178157, -0.61923322,
       -0.69886845, -0.10778848, -0.37014046,  0.83494059, -0.12688055])

`from numpy.random import ...`

- `rand` : random floats

- `randint` : random integers

- `randn` : standard normal distribution

- `permutation` : random permutation

- `normal` : Gaussian normal distribution

- `seed` : seed the random generator

<br>
<br>

# <center>Questions?</center>
<br>
<br>